config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root :to => "public/homes#top"
  namespace :public do
    get 'customers/withdrawal_check'
    patch 'customers/withdrawal'
    resources :directmails, only: [:new, :index, :show, :create]
    #resources :posts
    resources :customers, only: [:index, :show, :edit, :update]
    get "/about" => "homes#about"

    # ↓ コメント機能
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy] #イイね機能
    end
    
    # DM機能
    resources :directmail, only: [:new, :create]

    # フォロー機能 ネストさせる
    resources :customers do
      resource :relationships, only: [:create, :destroy]
      get 'relationships' => 'customers#followings', as: 'followings'
      get 'reverse_of_relationships' => 'customers#followers', as: 'followers'
    end

    get "/search" => "searches#search"
  end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :posts, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :destroy]
    get 'homes/top'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :favorites, dependent: :destroy #イイね機能
  has_many :post_comments, dependent: :destroy #コメント機能

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "reverse_of_relationships_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :relationships
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "relationships_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :reverse_of_relationships

  has_one_attached :image #画像投稿機能end
  
  # DM機能
  has_many :directmail, dependent: :destroy


  # ↓ 画像投稿機能
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
 end

 # フォローしたときの処理
  def follow(customer_id)
    relationships.create(reverse_of_relationships_id: customer_id)
  end

  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(reverse_of_relationships_id: customer_id).destroy
  end

  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end

   # 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      Customer.where(name: content)
    elsif method == 'forward'
      Customer.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Customer.where('name LIKE ?', '%' + content)
    else
      Customer.where('name LIKE ?', '%' + content + '%')
    end
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

  # ゲストログインで会員情報編集できないようにする
  def ensure_guest_user
    @customer = Customer.find(params[:id])
    if @customer.name == "guestuser"
      redirect_to customer_path(current_customer) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts
   end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: !@customer.is_deleted) #有効か退会か反転させる
    redirect_to admin_customers_path
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>会員一覧</h2>
        <table class="table">
          <thead>
            <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>会員ステータス</th>
                <th>ステータス変更</th>
            </tr>
          </thead>

          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <th>
                  <%= customer.id %>
                </th>
                <th>
                  <%= link_to customer.name, admin_customer_path(customer.id) %>
                </th>
                <th>
                  <%= customer.email %>
                </th>
                <th>
                  <%= customer.is_deleted ? '退会' : '有効' %>
                </th>
                <th>
                  <%= link_to admin_customer_path(customer), method: :delete do %>
                    <%= customer.is_deleted ? '有効にする' : '退会にする' %>
                  <% end %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>

        </div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">

            <h2><%= @customer.name %>さんの投稿一覧</h2>

              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <th>推し</th>
                    <th>募集名</th>
                    <th>募集内容</th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <% @posts.each do |post| %>
                    <tr>
                      <td>
                        <%= post.oshi_name %>
                      </td>
                      <td>
                        <%= post.post_name %>
                      </td>
                      <td>
                        <%= post.post_content %>
                      </td>
                      <td>
                        <%= link_to 'Destroy', admin_post_path(post.id), method: :delete,  class: 'btn btn-sm btn-danger destroy_book_58920', "data-confirm" => "本当に消しますか？"%></td>
                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>

          <%= link_to '会員一覧ページに戻る', admin_customers_path %>

        </div>
    </div>
</div>