config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root :to => "public/homes#top"
  namespace :public do
    get 'customers/withdrawal_check'
    patch 'customers/withdrawal'
    resources :directmails, only: [:new, :index, :show, :create]
    #resources :posts
    resources :customers, only: [:index, :show, :edit, :update]
    get "/about" => "homes#about"

    # ↓ コメント機能
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy] #イイね機能
    end
    
    # DM機能
    resources :directmail, only: [:new, :create]

    # フォロー機能 ネストさせる
    resources :customers do
      resource :relationships, only: [:create, :destroy]
      get 'relationships' => 'customers#followings', as: 'followings'
      get 'reverse_of_relationships' => 'customers#followers', as: 'followers'
    end

    get "/search" => "searches#search"
  end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :posts, only: [:index, :destroy]
    resources :customers, only: [:index, :show, :destroy]
    get 'homes/top'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OshitomoRoom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッター-->
    <header>
      <nav class='navbar navbar-expand-md navbar-light bg-light'>
        <%= link_to root_path, class: 'navbar-brand' do %>
          推し友 <i class="fas fa-heart"></i> ROOM
        <% end %>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class='collapse navbar-collapse justify-content-end' id="navbarNav">
          <ul class='navbar-nav'>

            <!--↓会員がログインしているとき↓-->
            <% if customer_signed_in? %>
              <!--マイページボタン-->
              <li class="nav-item">
                <%= link_to public_customer_path(current_customer.id), class:'nav-link text-right fontlist' do %>
                  <i class="fas fa-heart"></i> マイページ
                <% end %>
              </li>

              <!--推し友を探すボタン-->
              <li class="nav-item">
                <%= link_to public_customers_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-user"></i> 推し友をさがす
                <% end %>
              </li>
              <!--募集をさがすボタン-->
              <li class="nav-item">
                <%= link_to public_posts_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-comment"></i> 募集をさがす
                <% end %>
              </li>
              
              <!--ダイレクトメールボタン-->
              <!--
               <li class="nav-item">
                <%#= link_to public_directmails_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-envelope"></i> ダイレクトメール
                <%# end %>
              </li>
              -->
              
              <!--ログアウト-->
              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class:'nav-link fontlist' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>

            <!--↓管理者がログインしているとき↓-->
            <% elsif admin_signed_in? %>
              <!--会員一覧ボタン-->
              <li class="nav-item">
                <%= link_to admin_customers_path, class:'nav-link fontlist' do %>
                   <i class="fas fa-user"></i> 会員一覧
                <% end %>
              </li>
              <!--投稿一覧ボタン-->
              <li class="nav-item">
                <%= link_to admin_posts_path, class:'nav-link fontlist' do %>
                   <i class="fas fa-comment"></i> 投稿一覧
                <% end %>
              </li>
              <!--ログアウト-->
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete,class:'nav-link fontlist' do%>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>

            <!--↓ログインしていないとき↓-->
            <% else %>
               <!--HOMEボタン-->
              <li class="nav-item">
                <%= link_to root_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-home"></i> HOME
                <% end %>
              </li>
              <!--推し友ROOMについてボタン-->
              <li class="nav-item">
                <%= link_to public_about_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-heart"></i> 推し友ROOMについて
                <%end%>
              </li>
              <!--新規会員登録ボタン-->
              <li class="nav-item">
                <%= link_to new_customer_registration_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <!--ログインボタン-->
              <li class="nav-item">
                <%= link_to new_customer_session_path, class:'nav-link fontlist' do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
            <!--/div-->
            </ul>
        </div>
      </nav>

      <div class="container px-5 px-sm-0" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="row">
          <div class="col-md-3">
          </div>
          <!-- 検索機能 -->
          <div class="col-md-8 offset-md-1">
            <% if customer_signed_in? %>
              <%= form_with url: public_search_path, method: :get, local: true do |f| %>
                <%= f.text_field :content %>
                <%= f.select :model, options_for_select({ "推し友をさがす" => "customer", "募集をさがす" => "post" }) %>
                <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
                <%= f.submit '検索' %>
               <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </header>


    <!--メイン-->
    <main>
    <%= yield %>

    </main>


    <!--フッター-->
    <footer class='fixed-bottom'>
      <div class='p-auto py-4 footer-text-color text-center'>
        <p>推し友ROOM</p>
      </div>
    </footer>

    </footer>

  </body>
</html>